### ISSUE TITLE
Remove or redefine missing i18n messages "liberty-btn-close" and "liberty-btn-save-changes"

### ISSUE THREAD

**Issue by mary-kate** [librewiki/liberty-skin#13]
The i18n messages `liberty-btn-close` and `liberty-btn-save-changes` got removed from the English i18n JSON file in aa86154210db82ee136d6ac76e6410b10adc7e53 by @revi, but to this day they're seemingly "used" in the `div.modal-footer` element of the login dialog (which is only shown to anons), **but** that element is always (?) visually hidden via CSS...

As a side note, it might be worthwhile to look into the [OOJsUIAjaxLogin extension](https://www.mediawiki.org/wiki/Extension:OOJsUIAjaxLogin) and see if using that extension would make more sense than to have the skin provide such a feature. (Granted, the extension _is_ formally unmaintained but it worked just fine the last time I tried and it's not like it's _the_ most complex piece of software out there, so it probably won't need much maintenance going forward.)

**Comment by zlzleking** [comment]
it seems to be added oct. 2017 by commit 97442f985cb3eb202981f53207a83b694970c01f, i deleted this code from templete.
