### ISSUE TITLE
Skins should no longer output HTML and head tag

### ISSUE THREAD

**Issue by jdlrobson** [librewiki/liberty-skin#16]
Git lab reference: https://gitlab.com/librewiki/Liberty-MW-Skin/-/merge_requests/123#note_1193121732

**Comment by jdlrobson** [comment]
@zlzleking wrote
> First : we moved main repo to github [https://github.com/librewiki/liberty-skin]
Liberty skin uses many head elements and meta tags. If we apply this, many elements will go inside to body tag.
Following the intent of MediaWiki 1.39, it seems that many features of Liberty skins will have to be removed.

I don't think so. You can still modify the head element to add meta tags (making sure to check the skin key to see if you are in Liberty skin), but to do this you should make use of the https://www.mediawiki.org/wiki/Manual:Hooks/BeforePageDisplay hook or extend [Skin::initPage](https://gerrit.wikimedia.org/g/mediawiki/skins/BlueSpiceDiscovery/+/3718821de157f54c9de49fcf1d5f62a76c1c2e13/src/Skin.php#113). This change is only changing where and how the head element and scripts are outputted for greater compatibility with extensions.

Let me know if you still have any questions!

**Comment by zlzleking** [comment]
resolved after liberty 1.13
