### ISSUE TITLE
Make it possible to run the Liberty skin without third-party CSS/JS dependencies

### ISSUE THREAD

**Issue by mary-kate** [librewiki/liberty-skin#19]
Currently a bunch of external assets (FontAwesome from FontAwesome.com, other fonts mainly/only (?) for supporting Korean, share-api-polyfill from unpkg.com) are loaded _unconditionally_ in `SkinLiberty#setupCss`. While this may work just as intended from a functional point of view and be totally acceptable for a lower-traffic MediaWiki instance, this would make Liberty a no-go for more privacy-conscious setups; for example, the Wikimedia Foundation's sites.*

Ideally there'd be a configuration global that could and should be explicitly enabled by the end-user (sysadmin) in the wiki's `LocalSettings.php` to enable loading assets from external servers.
Google AdSense JS is a notable exception to that since it cannot be self-hosted; but the scenario I want to see is that with ads **turned off**, Liberty makes _no_ connections to external servers.

* I want to note that while I personally don't think we're seeing Liberty on WMF servers anytime soon, especially in the current political climate when it comes to skins, the WMF as the biggest MediaWiki user and developer is still an organization that cannot be ignored, and I find the policy of self-hosting as much as possible and avoiding external dependencies where and when possible a very reasonable policy.

**Comment by zlzleking** [comment]
We currently have plans to separate many features for librewiki from the libre skin's code into separate extensions.(eg. fonts)

In the long term, we plan to remove all third party css/js except the fontawethome and share api.
