### ISSUE TITLE
Error: Call to undefined function WikiPageFactory()

### ISSUE THREAD

**Issue by jdlrobson** [librewiki/liberty-skin#21]
Seen in MediaWiki 1.41. Fatal on page load.
I've stopped featuring the skin on https://skins.wmcloud.org/ while this is broken.

**Comment by Hoto-Cocoa** [comment]
Fixed by [a38316e](https://github.com/librewiki/liberty-skin/commit/a38316e302842425164020b679b9536d155371c5).
