### ISSUE TITLE
INstallationproblem

### ISSUE THREAD

**Issue by gtbu** [librewiki/liberty-skin#6]
After installation on mw1.27.4 and php 7 (xampp)  i get : 
Notice: Undefined index: notifications-alert in L:\xammp7025\htdocs\mw1274\skins\liberty\LibertyTemplate.php on line 638 .... Notice: Undefined index: notifications-message in L:\xammp7025\htdocs\mw1274\skins\liberty\LibertyTemplate.php on line 639

(I was at https://issue.librewiki.net/search/query/ryjJBqxqTfRS/#R - but could not publish an issue...)

**Comment by revi** [comment]
Hoi, phabricator instance admin here. (I'm not part of org for some reason) What was the error message you got?

And you were using [correct form](https://issue.librewiki.net/maniphest/task/edit/form/1/), right?

**Comment by gtbu** [comment]
Please see above the error 👍 Notice: Undefined index: notifications-alert in L:\xammp7025\htdocs\mw1274\skins\liberty\LibertyTemplate.php on line 638 .... Notice: Undefined index: notifications-message in L:\xammp7025\htdocs\mw1274\skins\liberty\LibertyTemplate.php on line 639

**Comment by revi** [comment]
I meant the Phabricator error (._.
